//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_filasordenes
    {
        public int id { get; set; }
        public int orden_id { get; set; }
        public int producto_id { get; set; }
        public int cantidad { get; set; }
    
        public virtual ordenes ordenes { get; set; }
        public virtual productos productos { get; set; }
    }
}
