//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_albepruebae3Entities : DbContext
    {
        public db_albepruebae3Entities()
            : base("name=db_albepruebae3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_filasordenes> C_filasordenes { get; set; }
        public virtual DbSet<ordenes> ordenes { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<v_ordenes> v_ordenes { get; set; }
    }
}
