//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ordenes
    {
        public string nombre_usuario { get; set; }
        public string apellidos_usuario { get; set; }
        public int numero_orden { get; set; }
        public Nullable<System.DateTime> fecha_orden { get; set; }
        public string marca_producto { get; set; }
        public string nombre_producto { get; set; }
        public decimal precio_producto { get; set; }
        public int cantidad_producto { get; set; }
    }
}
